version: '3'

services:

        api:
                image: yourfriendbober/nginx_api
                restart: always
                ports: 
                        - 4000:4000

        nginx_api:
                build: ./
                container_name: nginx_api
                ports:
                        - 8081:8081
                links:
                        - api
