---
  - name: Create a new Demo EC2 instance # for success work this playbook needs use python2.7
    hosts: localhost
    connection: local
    # gather_facts: False #this string for launching EC2
    # tags: provisioning
    # required parameters
    vars:
      region: us-east-2
      instance_type: t2.micro
      security_group: mev-task
      ami: ami-05c1fa8df71875112 #Ubuntu 18.04 LTS - free tier
      keypair: third-ubuntu
      count: 1
      aws_access_key: xxx
      aws_secret_key: xxxxxx
    vars_files:
      - aws_keys2.yml
            
    tasks:
      - name: Create a security group
        local_action:
          module: ec2_group
          name: "{{ security_group }}"
          description: Security Group for MEV EC2 Servers
          region: "{{ region }}"
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
          rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 80 #http in the fact
              to_port: 80
              cidr_ip: 0.0.0.0/0
          rules_egress:
            - proto: all
              cidr_ip: 0.0.0.0/0

      - name: Amazon EC2 | Create Key
        ec2_key:
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
          name: "{{ keypair }}"
          region: "{{ region }}"
        
      - name: Create an ec2 instance
        ec2:
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
          key_name: "{{ keypair }}"
          group: "{{ security_group }}"
          instance_type: "{{ instance_type }}"
          image: "{{ ami }}"
          wait: true
          region: "{{ region }}"
          count: "{{ count }}"
          count_tag:
            Name: Demo
          instance_tags:
            Name: Demo
          vpc_subnet_id: subnet-941e14fc
          assign_public_ip: yes
        register: ec2
