---
- hosts: localhost
  become: yes
  
  tasks:
  - name: Install prerequisites
    apt:
      name: ['apt-transport-https','ca-certificates','curl','gnupg2','software-properties-common']
      update_cache: yes

  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

  - name: Install Docker
    apt:
      name: docker-ce
      update_cache: yes

  - name: Install 'docker' pip packege
    become: yes
    become: root
    pip:
      name: ['docker', 'docker-compose']

  - name: Install Docker-compose
    become: yes
    #  shell: curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    get_url:
      url: "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-{{ansible_system}}-{{ansible_architecture}}"
      dest: /usr/local/bin/docker-compose
      mode: +x

  - name: Start service, if not started
    # become: yes
    # become_user: root
    service:
      name: docker
      state: started
      enabled: yes

#  - name: Install Nginx
#    apt: 
#      name: nginx 
#      state: latest
#      update_cache: yes

#  - name: Start Nginx
#    service:
#      name: nginx
#      state: started

  - name: Create user 'operator'
    become: yes
    become_user: root
    user:
      name: operator
      shell: /bin/bash
      groups: adm,sudo,docker
      append: yes

#  - name: copy the nginx config file and restart nginx
#      copy:
#        src: /home/foo/static_site.cfg
#        dest: /etc/nginx/sites-available/static_site.cfg
        
#  - name: create symlink
#    file:
#      src: /etc/nginx/sites-available/static_site.cfg
#      dest: /etc/nginx/sites-enabled/default
#      state: link

#  - name: copy the content of the web site
#    copy:
#      src: /home/foo/static-site-src/
#      dest: /home/foo/static-site

#  - name: restart nginx
#    service:
#      name: nginx
#      state: restarted    
